server:
  port: 8764
  
spring:
  application:
    name: service-consumer-ribbon
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true #These 2 lines are key for config server searching
        service-id: config-server #service name of config server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/